### PR TITLE
Fixed Exception Mechanism

### PR DESCRIPTION
**Pull request by XedinUnknown**
Aims to incorporate solution for #2.

### CODE REVIEW

**Comment by XedinUnknown** [comment]
A problem with the "throw instead of create" tactic for exceptions is that the line immediately after that does not get executed, and does not appear to be tested by code coverage reports. Returning `null` there is  even worse, because that line becomes meaningful, and yet untested. The code coverage analyzer cannot understand that the `_throw*Exception()` method **always** throws.

**Review by mecha — APPROVED** [review]
LGTM

**Comment by XedinUnknown** [comment]
Looks like complete code coverage may be achieved by using redundant `throw`, [like this][1].

[1]: https://github.com/Dhii/output-renderer-abstract/pull/4/commits/8f51a47d0be2e1ba3afb476c4a79d30eb765f2b6#diff-04df34e5be950faebc302e7c6a722e78R35

**Comment by mecha** [comment]
@XedinUnknown Wow that's weird.

**Pull request merged**
